package com.cerbon.adorable_eggs.config;

import com.cerbon.adorable_eggs.AdorableEggs;
import me.shedaniel.autoconfig.ConfigData;
import me.shedaniel.autoconfig.annotation.Config;

@Config(name = AdorableEggs.MOD_ID)
public class ADEConfig implements ConfigData {

    public boolean isPlaceEggsEnabled = true;

    public float allayEggDropChance           = 1f/25f;
    public float armadilloEggDropChance       = 1f/25f;
    public float breezeEggDropChance          = 1f/25f;
    public float camelEggDropChance           = 1f/25f;
    public float catEggDropChance             = 1f/25f;
    public float creakingEggDropChance        = 1f/25f;
    public float dolphinEggDropChance         = 1f/25f;
    public float elderGuardianEggDropChance   = 1f/25f;
    public float endermiteEggDropChance       = 1f/25f;
    public float evokerEggDropChance          = 1f/25f;
    public float foxEggDropChance             = 1f/25f;
    public float ironGolemEggDropChance       = 1f/25f;
    public float pandaEggDropChance           = 1f/25f;
    public float polarBearEggDropChance       = 1f/25f;
    public float pufferfishEggDropChance      = 1f/25f;
    public float ravagerEggDropChance         = 1f/25f;
    public float skeletonHorseEggDropChance   = 1f/25f;
    public float snifferEggDropChance         = 1f/25f;
    public float striderEggDropChance         = 1f/25f;
    public float traderLlamaEggDropChance     = 1f/25f;
    public float wanderingTraderEggDropChance = 1f/25f;
    public float wardenEggDropChance          = 1f/25f;
    public float enderDragonEggDropChance     = 1f/25f;
    public float witherEggDropChance          = 1f/25f;
    public float zoglinEggDropChance          = 1f/25f;
    public float zombieHorseEggDropChance     = 1f/25f;
    public float axolotlEggDropChance         = 1f/50f;
    public float tadpoleEggDropChance         = 1f/50f;
    public float batEggDropChance             = 1f/50f;
    public float beeEggDropChance             = 1f/50f;
    public float boggedEggDropChance          = 1f/50f;
    public float donkeyEggDropChance          = 1f/50f;
    public float frogEggDropChance            = 1f/50f;
    public float ghastEggDropChance           = 1f/50f;
    public float glowSquidEggDropChance       = 1f/50f;
    public float goatEggDropChance            = 1f/50f;
    public float guardianEggDropChance        = 1f/50f;
    public float hoglinEggDropChance          = 1f/50f;
    public float horseEggDropChance           = 1f/50f;
    public float llamaEggDropChance           = 1f/50f;
    public float mooshroomEggDropChance       = 1f/50f;
    public float muleEggDropChance            = 1f/50f;
    public float ocelotEggDropChance          = 1f/50f;
    public float parrotEggDropChance          = 1f/50f;
    public float phantomEggDropChance         = 1f/50f;
    public float rabbitEggDropChance          = 1f/50f;
    public float shulkerEggDropChance         = 1f/50f;
    public float snowGolemEggDropChance       = 1f/50f;
    public float strayEggDropChance           = 1f/50f;
    public float tropicalFishEggDropChance    = 1f/50f;
    public float turtleEggDropChance          = 1f/50f;
    public float vexEggDropChance             = 1f/50f;
    public float villagerEggDropChance        = 1f/50f;
    public float wolfEggDropChance            = 1f/50f;
    public float codEggDropChance             = 1f/50f;
    public float salmonEggDropChance          = 1f/50f;
    public float blazeEggDropChance           = 1f/100f;
    public float caveSpiderEggDropChance      = 1f/100f;
    public float huskEggDropChance            = 1f/100f;
    public float piglinBruteEggDropChance     = 1f/100f;
    public float pillagerEggDropChance        = 1f/100f;
    public float silverfishEggDropChance      = 1f/100f;
    public float squidEggDropChance           = 1f/100f;
    public float vindicatorEggDropChance      = 1f/100f;
    public float witchEggDropChance           = 1f/100f;
    public float witherSkeletonEggDropChance  = 1f/100f;
    public float zombieVillagerEggDropChance  = 1f/100f;
    public float drownedEggDropChance         = 1f/250f;
    public float endermanEggDropChance        = 1f/250f;
    public float piglinEggDropChance          = 1f/250f;
    public float zombifiedPiglinEggDropChance = 1f/250f;
    public float chickenEggDropChance         = 1f/500f;
    public float cowEggDropChance             = 1f/500f;
    public float creeperEggDropChance         = 1f/500f;
    public float magmaCubeEggDropChance       = 1f/500f;
    public float pigEggDropChance             = 1f/500f;
    public float slimeEggDropChance           = 1f/500f;
    public float spiderEggDropChance          = 1f/500f;
    public float zombieEggDropChance          = 1f/500f;
    public float skeletonEggDropChance        = 1f/500f;
    public float sheepEggDropChance           = 1f/500f;
}
